name: Deploy to Docker Hub

on:
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Build and Push to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REGISTRY: docker.io
        DOCKER_IMAGE: <user_name>/<image_name>
        DOCKER_TAG: ${{ github.ref }}
      with:
        args: build -t ${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} .
    - name: Deploy to Dev/Prod
      if: github.ref == 'dev'
      run: docker push ${{ env.DOCKER_IMAGE }}:dev
      if: github.ref == 'prod'
      run: docker push ${{ env.DOCKER_IMAGE }}:prodname: ci/cd deployment


on:
  push:
    branches:
      - master
      
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
      
      - name: Install Packages
        run: npm 1
  
  cd:
    runs-on: self-hosted
    needs: [ci]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection:latest
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection:latest

  #steps: Deploy on Azure