name: ci/cd deployment


on:
  push:
    branches:
      - dev
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '14.x'
      
      - name: Install Packages
        run: npm i
  
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker Image
        run: docker build . --file Dockerfile.txt --tag ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection:latest
      - name: Docker push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dockerhub-connection:latest

  #steps: Deploy on Azure