name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Scripts
        run: |
          docker build -t app .
          docker login -u sudhirsonawane5 -p dckr_pat_y17oTOubREm2JIXnx9sfX5N5qew
          docker tag app sudhirsonawane5/dockerhub-connection
          docker push sudhirsonawane5/dockerhub-connection