name: Multi-Branch Pipeline

on:
  push:
    branches:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Docker
      uses: docker/setup-docker-action@v1
    - name: Build and Push Docker Image
      uses: Dockerfile/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sudhirsonawane5/dockerhub-connection

    - name: Deploy to DockerHub
      uses: Dockerfile/deploy-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sudhirsonawane5/dockerhub-connection
